### ISSUE TITLE
GHC 9.2 support

### ISSUE THREAD

**Issue by sofia-m-a** [mstksg/functor-combinators#6]
GHC  9.2, and base-4.16, remove the deprecated `Data.Semigroup.Option` which is given instances in this library. Therefore, building on GHC 9.2 gives the error `Not in scope: type constructor or class ‘Semigroup.Option’`. Note that the dependency bounds of the library advertise 4.16-compatibility.

So we either need a new version that removes these instances, or use CPP based on the GHC version to only enable them on pre-GHC9.2 builds

**Comment by mstksg** [comment]
Fix pushed to hackage, thanks for reporting :)
